on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
      - name: Clone
        if: steps.release.outputs.release_created
        uses: actions/checkout@v5
      - name: Use Node.js 22.x
        if: steps.release.outputs.release_created
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install deps
        if: steps.release.outputs.release_created
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build source
        if: steps.release.outputs.release_created
        run: npm run build
      - name: Publish
        if: steps.release.outputs.release_created
        run: npm publish
